export const CHANGE_RADIO_SELECT = 'CHANGE_RADIO_SELECT';
export const CHANGE_INPUT_SEARCH = 'CHANGE_INPUT_SEARCH';
export const CHANGE_HEADER_SCROLL = 'CHANGE_HEADER_SCROLL';
export const CHANGE_FILMS_ARRAY = 'CHANGE_FILMS_ARRAY';
